[build]
  publish = "deploy-to-netlify"
  command = "echo 'No build needed - using static files'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"